//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormPris
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int ID_Journal { get; set; }
        public System.DateTime Date_Given { get; set; }
        public System.DateTime Date_Return_Expected { get; set; }
        public System.DateTime Date_Return_Actual { get; set; }
        public Nullable<int> Bill_Number { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<double> Bill_Sum { get; set; }
        public string Article { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public int Librarian_ID { get; set; }
        public int Book_ID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Student Student { get; set; }
    }
}
