//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NormPris
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Journal = new HashSet<Journal>();
        }
    
        public int ID_Student { get; set; }
        private string name;
        public string Name 
        { 
            get
            {
                return name;
            }
            set
            {
                name = value.Trim();
            }
        }
        public string Lib_Card_Number { get; set; }
        public Nullable<System.DateTime> Lib_Card_Date { get; set; }
        public string Stud_Card_Number { get; set; }
        public System.DateTime Stud_Card_Date { get; set; }
        public int Group_ID { get; set; }
    
        public virtual Group Group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journal { get; set; }
        public override string ToString()
        {
            return Name;
        }
    }
}
